### PR TITLE
Create factory method on ApifyDatasetLoader

### PR DESCRIPTION
**Pull request by jacoblee93**
CC @jirimoravcik @jancurn this is roughly what I have in mind - does this make sense to you?

### CODE REVIEW

**Comment by jacoblee93** [comment]
I also moved `datasetMappingFunction` into the config object. This way its purpose is clearer when creating a client, and would make refactoring easier in the future if maybe someday it could be set on Apify's end/defaulted to some reasonable value.

We also don't need the awkward `await import` thing for optional deps anymore as we can put this module in its own entrypoint.

**Comment by jancurn** [comment]
@jacoblee93 Wow, many thanks for your changes. I see you already merged them to the main repo? In that case, I assume we can just close this

**Comment by jacoblee93** [comment]
Yes! I accidentally and prematurely deployed the docs here:

https://js.langchain.com/docs/modules/indexes/document_loaders/examples/web_loaders/apify_dataset

The actor call took a really long time (30 minutes) on the LangChain docs so I should probably go back and use a different example though. Do you have a faster scraping example site?

**Comment by jacoblee93** [comment]
Oh hey, also @jirimoravcik are you on Twitter? Doing a release announcement thread soon and would give you a shoutout.

**Comment by jancurn** [comment]
Hey @jacoblee93, @jirimoravcik doesn't have a twitter. It would be awesome if you could tag https://twitter.com/apify

**Pull request closed without merging**
